// app/form1/config.js

export const CAR_PARTS = [
    {
        id: 'kapota',
        label: 'Kapota',
        category: 'horizontal',
        x: 50,
        y: 139,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'strecha',
        label: 'Střecha',
        category: 'horizontal',
        x: 50,
        y: 145,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'levyPredniBlatnik',
        label: 'Levý přední blatník',
        category: 'vertical',
        x: 50,
        y: 152,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'pravyPredniBlatnik',
        label: 'Pravý přední blatník',
        category: 'vertical',
        x: 50,
        y: 159,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'levePredniDvere',
        label: 'Levé přední dveře',
        category: 'vertical',
        x: 50,
        y: 165,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'pravePredniDvere',
        label: 'Pravé přední dveře',
        category: 'vertical',
        x: 50,
        y: 172,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'leveZadniDvere',
        label: 'Levé zadní dveře',
        category: 'vertical',
        x: 50,
        y: 179,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'praveZadniDvere',
        label: 'Pravé zadní dveře',
        category: 'vertical',
        x: 50,
        y: 186,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'leveZadniBlatniky',
        label: 'Levý zadní blatník',
        category: 'vertical',
        x: 50,
        y: 192,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'pravyZadniBlatnik',
        label: 'Pravý zadní blatník',
        category: 'vertical',
        x: 50,
        y: 199,
        lakX: 100,
        vymenaX: 120,
    },
    {
        id: 'levyRam',
        label: 'Levý rám',
        category: 'frame',
        x: 50,
        y: 206,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'pravyRam',
        label: 'Pravý rám',
        category: 'frame',
        x: 50,
        y: 211,
        lakX: 100,
        vymenaX: 118,
    },
    {
        id: 'zadniKapota',
        label: 'Zadní kapota',
        category: 'frame',
        x: 50,
        y: 219,
        lakX: 100,
        vymenaX: 120,
    },
];

export const VEHICLE_BRANDS = [
    'Alfa Romeo',
    'Audi',
    'BMW',
    'Citroën',
    'Dacia',
    'Fiat',
    'Ford',
    'Honda',
    'Hyundai',
    'KIA',
    'Mazda',
    'Mercedes-Benz',
    'Mitsubishi',
    'Nissan',
    'Opel',
    'Peugeot',
    'Renault',
    'Seat',
    'Subaru',
    'Suzuki',
    'Škoda',
    'Toyota',
    'Volkswagen',
    'Volvo',
    'Jiné - upřesním níže',
];

export const DENT_DIAMETERS = [
    20, 30, 40, 60, 80, 100, 130, 160, 190, 220, 250, 280, 310, 340, 370, 400,
    430, 460, 490, 520, 550, 580, 610, 640, 670, 700,
];

export const ADDITIONAL_DAMAGES = [
    { id: 'extra1', label: 'Další poškození 1', category: 'extra' },
    { id: 'extra2', label: 'Další poškození 2', category: 'extra' },
    { id: 'extra3', label: 'Další poškození 3', category: 'extra' },
    { id: 'extra4', label: 'Další poškození 4', category: 'extra' },
    { id: 'extra5', label: 'Další poškození 5', category: 'extra' },
    { id: 'extra6', label: 'Další poškození 6', category: 'extra' },
    { id: 'extra7', label: 'Další poškození 7', category: 'extra' },
    { id: 'extra8', label: 'Další poškození 8', category: 'extra' },
    { id: 'extra9', label: 'Další poškození 9', category: 'extra' },
    { id: 'extra10', label: 'Další poškození 10', category: 'extra' },
];

const BASIC_CONFIG = {
    isGlobal: false,
    showExtraContact: false,
    requiredFields: ['vehicleSPZ'],
    requiredPhotos: [
        'zapisOPoskozeni',
        'pohledZePredu',
        'pohledZePreduZleva',
        'pohledZleva',
        'pohledZezaduZleva',
        'pohledZezadu',
        'pohledZezaduZprava',
        'pohledZprava',
        'pohledZepreduZprava',
        'STK',
        'VIN',
        'tachometr',
        'interier',
        'dodatecneFoto1',
        'dodatecneFoto2',
    ],
    insurers: [
        'Allianz',
        'AXA',
        'ČPP',
        'ČSOB Pojišťovna',
        'Direct',
        'Generali',
        'Kooperativa',
        'Pillow',
        'Servisní pojišťovna',
        'Slavia',
        'VZP',
        'Ostatní',
    ],
    hiddenFields: [],
    pdfBackground: '/zakazkovy_list_default.jpg',
    tableStartY: 107,
    signaturePos: [35, 276, 30, 10], // x, y, šířka, výška
    totalPricePos: [14, 256],
    txtPos: {
        technician: [133, 256],
        customerName: [14, 49],
        customerPhone: [122, 49],
        customerAddress: [14, 60],
        vehicleBrand: [14, 72],
        vehicleType: [65, 72],
        vehicleSPZ: [122, 72],
        vehicleVIN: [14, 83],
        vehicleDistance: [107, 83],
        vehicleYear: [136, 83],
        vehicleColor: [167, 83],
        insuranceCompany: [14, 94],
        insuranceNumber: [88, 94],
        serviceDate: [154, 94],
        notes: [134, 107], // Pozice pro detailNotes
    },
};

const GLOBAL_CONFIG = {
    isGlobal: true,
    showExtraContact: true,
    requiredFields: ['vehicleSPZ'],
    requiredPhotos: ['pohledZePredu', 'pohledZezadu'],
    insurers: ['Kooperativa', 'ČPP'],
    hiddenFields: [
        'vehicleVIN',
        'vehicleType',
        'vehicleYear',
        'vehicleDistance',
        'vehicleColor',
    ],
    pdfBackground: '/zakazkovy_list_globals.jpg',
    tableStartY: 100,
    signaturePos: [35, 276, 30, 10], // x, y, šířka, výška
    totalPricePos: [14, 256],
    txtPos: {
        technician: [133, 243],
        customerName: [14, 49],
        customerPhone: [122, 49],
        customerAddress: [14, 60],
        vehicleBrand: [14, 72],
        vehicleType: [65, 72],
        vehicleSPZ: [122, 72],
        vehicleVIN: [14, 83],
        vehicleDistance: [107, 83],
        vehicleYear: [136, 83],
        vehicleColor: [167, 83],
        insuranceCompany: [14, 83],
        insuranceNumber: [88, 83],
        serviceDate: [154, 83],
        notes: [134, 100], // Pozice pro detailNotes
    },
};

const CBAUTO_CONFIG = {
    isGlobal: false,
    showExtraContact: true,
    requiredFields: ['vehicleSPZ'],
    requiredPhotos: ['pohledZePredu', 'pohledZezadu'],
    insurers: [
        'Allianz',
        'AXA',
        'ČPP',
        'ČSOB Pojišťovna',
        'Direct',
        'Generali',
        'Kooperativa',
        'Pillow',
        'Servisní pojišťovna',
        'Slavia',
        'VZP',
        'Ostatní',
    ],
    hiddenFields: [
        'vehicleVIN',
        'vehicleType',
        'vehicleYear',
        'vehicleDistance',
        'vehicleColor',
    ],
    pdfBackground: '/zakazkovy_list_globals.jpg',
    tableStartY: 100,
    signaturePos: [35, 276, 30, 10], // x, y, šířka, výška
    totalPricePos: [14, 256],
    txtPos: {
        technician: [133, 243],
        customerName: [14, 49],
        customerPhone: [122, 49],
        customerAddress: [14, 60],
        vehicleBrand: [14, 72],
        vehicleType: [65, 72],
        vehicleSPZ: [122, 72],
        vehicleVIN: [14, 83],
        vehicleDistance: [107, 83],
        vehicleYear: [136, 83],
        vehicleColor: [167, 83],
        insuranceCompany: [14, 83],
        insuranceNumber: [88, 83],
        serviceDate: [154, 83],
        notes: [134, 100], // Pozice pro detailNotes
    },
};
export const USER_ROLES = {
    admin: BASIC_CONFIG,
    Vinicars: BASIC_CONFIG,
    Jirka: BASIC_CONFIG,
    Roman: BASIC_CONFIG,
    Talafova: BASIC_CONFIG,
    Hlavsova: BASIC_CONFIG,
    Horynova: BASIC_CONFIG,
    Global: GLOBAL_CONFIG,
    Autopalace: GLOBAL_CONFIG,
    CBservis: CBAUTO_CONFIG,
    CKservis: CBAUTO_CONFIG,
    TBRservis: CBAUTO_CONFIG,
    OLCservis: CBAUTO_CONFIG,
    SUMPservis: CBAUTO_CONFIG,
    Autosklo: CBAUTO_CONFIG,
    Uniqa: CBAUTO_CONFIG,
    Direct: CBAUTO_CONFIG,
    Pillow: CBAUTO_CONFIG,
    AUTOUH: CBAUTO_CONFIG,
    AUTONORD: CBAUTO_CONFIG,
    DIRECTAUTO: CBAUTO_CONFIG,
    BIRNE: CBAUTO_CONFIG,
    ALLIANZ: CBAUTO_CONFIG,
    AUTOLEAS: CBAUTO_CONFIG,
    DASPOL: CBAUTO_CONFIG,
    BOB: CBAUTO_CONFIG,
    ARVAL: CBAUTO_CONFIG,
    BUSINESS: CBAUTO_CONFIG,
    CSOB: CBAUTO_CONFIG,
    DOLAK: CBAUTO_CONFIG,
    KACMACEK: CBAUTO_CONFIG,
    AUTONOVA: CBAUTO_CONFIG,
};

export const getConfigForUser = (username) => {
    // Pokud jméno není v seznamu, vrátíme BASIC_CONFIG přes klíč 'admin'
    return USER_ROLES[username] || USER_ROLES['admin'];
};
